"""empty message

Revision ID: 087493055929
Revises: 4eaa8cd6908f
Create Date: 2021-11-20 11:34:53.739607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087493055929'
down_revision = '4eaa8cd6908f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'emal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emal', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
